### ISSUE TITLE
Link to the original paper

### ISSUE THREAD

**Issue by prafiles** [karpathy/paper-notes#1]
Hey I've been following your work since a long time now, and I yesterday took this link from twitter feed directing me to this repo containing your notes about the paper. However well written, I wish two more things:
1. Is there a public link to the paper (or some paid journal pointing to it?)
2. Is there any source available?

Sorry for bugging you.

Edit: Forgot to mention, this concerns matching networks only.

**Comment by Bleyddyn** [comment]
http://arxiv.org/abs/1606.04080v1

I haven't read the paper, yet, but scanning it I didn't see any link to source code.

**Comment by prafiles** [comment]
Thanks! Didn't expect such a quick response!
